import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Space_Grotesk } from 'next/font/google';

import '@/assets/styles/css/globals.css';

import { NAVIGATION_LINKS } from '@/libs/mock';
import ContextProvider from '@/store/context';

import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import Main from '@/components/layout/Main';
import Apollo from '@/components/layout/Apollo';

const aboreto = localFont({
    src: '../assets/fonts/aboreto/Aboreto-Regular.ttf',
    variable: '--font-aboreto',
});

const spaceGrotesk = Space_Grotesk({
    variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <ContextProvider>
            <html lang="en">
                <body className={`${aboreto.variable} ${spaceGrotesk.variable}`}>
                    <Apollo>
                        <Main>
                            <Header items={NAVIGATION_LINKS} />

                            <main>{children}</main>

                            <Footer />
                        </Main>
                    </Apollo>
                </body>
            </html>
        </ContextProvider>
    );
}
