/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Summaries".
 */
export type Summaries =
    | {
          title?: string | null;
          details?:
              | {
                    label?: (number | null) | Label;
                    value?: string | null;
                    id?: string | null;
                }[]
              | null;
          id?: string | null;
      }[]
    | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Prices".
 */
export type Prices =
    | {
          price: number;
          salePrice?: number | null;
          days: number;
          id?: string | null;
      }[]
    | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
    | 'Pacific/Midway'
    | 'Pacific/Niue'
    | 'Pacific/Honolulu'
    | 'Pacific/Rarotonga'
    | 'America/Anchorage'
    | 'Pacific/Gambier'
    | 'America/Los_Angeles'
    | 'America/Tijuana'
    | 'America/Denver'
    | 'America/Phoenix'
    | 'America/Chicago'
    | 'America/Guatemala'
    | 'America/New_York'
    | 'America/Bogota'
    | 'America/Caracas'
    | 'America/Santiago'
    | 'America/Buenos_Aires'
    | 'America/Sao_Paulo'
    | 'Atlantic/South_Georgia'
    | 'Atlantic/Azores'
    | 'Atlantic/Cape_Verde'
    | 'Europe/London'
    | 'Europe/Berlin'
    | 'Africa/Lagos'
    | 'Europe/Athens'
    | 'Africa/Cairo'
    | 'Europe/Moscow'
    | 'Asia/Riyadh'
    | 'Asia/Dubai'
    | 'Asia/Baku'
    | 'Asia/Karachi'
    | 'Asia/Tashkent'
    | 'Asia/Calcutta'
    | 'Asia/Dhaka'
    | 'Asia/Almaty'
    | 'Asia/Jakarta'
    | 'Asia/Bangkok'
    | 'Asia/Shanghai'
    | 'Asia/Singapore'
    | 'Asia/Tokyo'
    | 'Asia/Seoul'
    | 'Australia/Brisbane'
    | 'Australia/Sydney'
    | 'Pacific/Guam'
    | 'Pacific/Noumea'
    | 'Pacific/Auckland'
    | 'Pacific/Fiji';

export interface Config {
    auth: {
        tokens: TokenAuthOperations;
        users: UserAuthOperations;
    };
    blocks: {};
    collections: {
        media: Media;
        categories: Category;
        colors: Color;
        labels: Label;
        sizes: Size;
        tags: Tag;
        products: Product;
        productsCategories: ProductsCategory;
        tokens: Token;
        users: User;
        'payload-kv': PayloadKv;
        'payload-locked-documents': PayloadLockedDocument;
        'payload-preferences': PayloadPreference;
        'payload-migrations': PayloadMigration;
    };
    collectionsJoins: {};
    collectionsSelect: {
        media: MediaSelect<false> | MediaSelect<true>;
        categories: CategoriesSelect<false> | CategoriesSelect<true>;
        colors: ColorsSelect<false> | ColorsSelect<true>;
        labels: LabelsSelect<false> | LabelsSelect<true>;
        sizes: SizesSelect<false> | SizesSelect<true>;
        tags: TagsSelect<false> | TagsSelect<true>;
        products: ProductsSelect<false> | ProductsSelect<true>;
        productsCategories: ProductsCategoriesSelect<false> | ProductsCategoriesSelect<true>;
        tokens: TokensSelect<false> | TokensSelect<true>;
        users: UsersSelect<false> | UsersSelect<true>;
        'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
        'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
        'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
        'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    };
    db: {
        defaultIDType: number;
    };
    fallbackLocale: null;
    globals: {};
    globalsSelect: {};
    locale: null;
    user: Token | User;
    jobs: {
        tasks: unknown;
        workflows: unknown;
    };
}
export interface TokenAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
export interface UserAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
    id: number;
    alt: string;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
    id: number;
    typeHandle: string;
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
    id: number;
    typeHandle: string;
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    color?: string | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels".
 */
export interface Label {
    id: number;
    typeHandle: string;
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes".
 */
export interface Size {
    id: number;
    typeHandle: string;
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
    id: number;
    typeHandle: string;
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
    id: number;
    typeHandle: string;
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    url?: string | null;
    uri?: string | null;
    summaries?: Summaries;
    bookedDates?:
        | {
              from?: string | null;
              to?: string | null;
              id?: string | null;
          }[]
        | null;
    prices?: Prices;
    category?: (number | null) | Category;
    colors?: (number | Color)[] | null;
    sizes?: (number | Size)[] | null;
    tag?: (number | null) | Tag;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productsCategories".
 */
export interface ProductsCategory {
    id: number;
    typeHandle: string;
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    url?: string | null;
    uri?: string | null;
    category: number | Category;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tokens".
 */
export interface Token {
    id: number;
    title: string;
    updatedAt: string;
    createdAt: string;
    enableAPIKey?: boolean | null;
    apiKey?: string | null;
    apiKeyIndex?: string | null;
    collection: 'tokens';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: number;
    updatedAt: string;
    createdAt: string;
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    sessions?:
        | {
              id: string;
              createdAt?: string | null;
              expiresAt: string;
          }[]
        | null;
    password?: string | null;
    collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
    id: number;
    key: string;
    data:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
    id: number;
    document?:
        | ({
              relationTo: 'media';
              value: number | Media;
          } | null)
        | ({
              relationTo: 'categories';
              value: number | Category;
          } | null)
        | ({
              relationTo: 'colors';
              value: number | Color;
          } | null)
        | ({
              relationTo: 'labels';
              value: number | Label;
          } | null)
        | ({
              relationTo: 'sizes';
              value: number | Size;
          } | null)
        | ({
              relationTo: 'tags';
              value: number | Tag;
          } | null)
        | ({
              relationTo: 'products';
              value: number | Product;
          } | null)
        | ({
              relationTo: 'productsCategories';
              value: number | ProductsCategory;
          } | null)
        | ({
              relationTo: 'tokens';
              value: number | Token;
          } | null)
        | ({
              relationTo: 'users';
              value: number | User;
          } | null);
    globalSlug?: string | null;
    user:
        | {
              relationTo: 'tokens';
              value: number | Token;
          }
        | {
              relationTo: 'users';
              value: number | User;
          };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: number;
    user:
        | {
              relationTo: 'tokens';
              value: number | Token;
          }
        | {
              relationTo: 'users';
              value: number | User;
          };
    key?: string | null;
    value?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: number;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
    alt?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    color?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels_select".
 */
export interface LabelsSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes_select".
 */
export interface SizesSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    url?: T;
    uri?: T;
    summaries?: T | SummariesSelect<T>;
    bookedDates?:
        | T
        | {
              from?: T;
              to?: T;
              id?: T;
          };
    prices?: T | PricesSelect<T>;
    category?: T;
    colors?: T;
    sizes?: T;
    tag?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Summaries_select".
 */
export interface SummariesSelect<T extends boolean = true> {
    title?: T;
    details?:
        | T
        | {
              label?: T;
              value?: T;
              id?: T;
          };
    id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Prices_select".
 */
export interface PricesSelect<T extends boolean = true> {
    price?: T;
    salePrice?: T;
    days?: T;
    id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productsCategories_select".
 */
export interface ProductsCategoriesSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    url?: T;
    uri?: T;
    category?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tokens_select".
 */
export interface TokensSelect<T extends boolean = true> {
    title?: T;
    updatedAt?: T;
    createdAt?: T;
    enableAPIKey?: T;
    apiKey?: T;
    apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
    updatedAt?: T;
    createdAt?: T;
    email?: T;
    resetPasswordToken?: T;
    resetPasswordExpiration?: T;
    salt?: T;
    hash?: T;
    loginAttempts?: T;
    lockUntil?: T;
    sessions?:
        | T
        | {
              id?: T;
              createdAt?: T;
              expiresAt?: T;
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
    key?: T;
    data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
    document?: T;
    globalSlug?: T;
    user?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
    user?: T;
    key?: T;
    value?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
    name?: T;
    batch?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
    [k: string]: unknown;
}
